### ISSUE TITLE
Will this be released? 

### ISSUE THREAD

**Issue by jakupmichaelsen** [gep13-oss/gitpitch-vscode#49]
It would be great to have syntax higlighting available for GitPitch in VSCode. Will this every be released? :)

**Comment by gep13** [comment]
@jakupmichaelsen it is certainly on my list of things to do, but as yet, not in a position to release this no, as the extension doesn't actually do anything.  Currently, this just contains the scaffolding for the extension.

Syntax highlighting was not an immediate goal of the extension.  The first thing that I was working on was an outline view, which would allow easy navigation between slides in the slidedeck.

**Comment by jakupmichaelsen** [comment]
Ah that sounds like a very usefull feature :) Looking forward to trying it!
